routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\IndexController;
use App\Http\Controllers\ProductController;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\CategoryProductController;
use App\Http\Controllers\PostController;
use App\Http\Controllers\FrontendController;
use App\Http\Controllers\CartController;
use App\Http\Controllers\Controller;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

//Route::get('/home123', function () {
//    return view('frontend.home');
//});
//Route::get('/clone', 'FrontendController@getHome');
//Route::get('/clone', [
//    'uses' => 'FrontendController@getHome'
//]);

Route::get('/clone', [FrontendController::class,'getHome']);
Route::get('detail/{id}/', [FrontendController::class,'getDetail']);
Route::post('detail/{id}/', [FrontendController::class,'postComment']);


Route::get('detail/{id}/', [FrontendController::class,'getDetail']);

Route::get('search', [FrontendController::class,'getSearch']);

Route::group(['prefix' => 'cart'], function() {
    Route::get('add/{id}', [CartController::class, 'getAddCart']);
    Route::get('show', [CartController::class, 'getShowCart']);
    Route::get('delete/{id}', [CartController::class, 'getDeleteCart']);
    Route::get('update', [CartController::class, 'getUpdateCart']);
    Route::post('show', [CartController::class, 'postComplete']);
});

Route::get('complete',[CartController::class, 'getComplete']);

//Route::get('cart/add/{id}', [CartController::class,'getAddCart']);

Route::get('category-product/{id}/', [FrontendController::class,'getCategoryProduct']);

Route::get('/', [IndexController::class,'home']);

Route::get('/home', [HomeController::class, 'index'])->name('home');
Route::get('/test', function () {
   return view('layouts.master');
});
Route::get('/thu', function () {
   return view('test');
});
Auth::routes();

Route::resource('admin/product', ProductController::class);
Route::resource('admin/category-product', CategoryProductController::class);
Route::resource('admin/post', PostController::class);

resources/views/admin/category/create.blade.php
@extends('outline')


@section('content')
    <div class="container">
        <div class="card">
            <div class="card-header">
                <div class="row">
                    <div class="col-md-6">
                        <h3>Thêm sản phẩm</h3>
                    </div>
                    <div class="col-md-6">
                        <a href="{{route('categoryproduct.index')}}" class="btn btn-primary float-end">Danh sách danh mục sản phẩm</a>
                    </div>
                </div>
            </div>

            <div class="card-body">
                <form action="{{route('categoryproduct.store')}}" method="POST">
                    @csrf
                    <div class="row">
                        <div class="col-md-6">
                            <div class="form-group">
                                <strong>Tên sản phẩm</strong>
                                <input type="text" name="name" class="form-control" placeholder="Nhập tên sản phẩm">
                            </div>
                            <div class="form-group">
                                <strong>Mô tả</strong>
                                <input type="text" name="description" class="form-control" placeholder="Nhập mô tả sản phẩm">
                            </div>
                            <div class="form-group">
                                <strong>Giá</strong>
                                <input type="text" name="price" class="form-control" placeholder="Nhập giá">
                            </div>
                            <div class="form-group">
                                <strong>Số lượng</strong>
                                <input type="number" name="quantity" class="form-control" placeholder="Nhập giá">
                            </div>
                            <div class="form-group">
                                <strong>Màu</strong>
                                <input type="text" name="color" class="form-control" placeholder="Nhập màu sắc">
                            </div>
                            <div class="form-group">
                                <strong>Ngày nhập kho</strong>
                                <input type="date" name="ngay_nhap" class="form-control">
                            </div>

                            <div class="form-group">
                                <label >Thuộc danh mục</label>
                                <select name="category_id" class="custom-select">
                                    @foreach($category as $key => $value)
                                        <option value="{{$value->id}}">{{$value->name}}</option>
                                    @endforeach
                                </select>
                            </div>
                        </div>
                    </div>
                    <button type="submit" class="btn btn-success mt-2">Lưu</button>
                </form>

            </div>
        </div>
    </div>
@endsection

resources/views/admin/category/edit.blade.php
@extends('outline')


@section('content')
    <div class="container">
        <div class="card">
            <div class="card-header">
                <div class="row">
                    <div class="col-md-6">
                        <h3> Sửa sản phẩm</h3>
                    </div>
                    <div class="col-md-6">
                        <a href="{{route('product.index')}}" class="btn btn-primary float-end">Danh sách sản phẩm</a>
                    </div>
                </div>
            </div>

            <div class="card-body">
                <form action="{{route('product.store')}}" method="POST">
                    @csrf
                    <div class="row">
                        <div class="col-md-6">
                            <div class="form-group">
                                <strong>Tên sản phẩm</strong>
                                <input type="text" name="name" class="form-control" placeholder="Nhập tên sản phẩm">
                            </div>
                            <div class="form-group">
                                <strong>Mô tả</strong>
                                <input type="text" name="description" class="form-control" placeholder="Nhập mô tả sản phẩm">
                            </div>
                            <div class="form-group">
                                <strong>Giá</strong>
                                <input type="text" name="price" class="form-control" placeholder="Nhập giá">
                            </div>
                            <div class="form-group">
                                <strong>Số lượng</strong>
                                <input type="number" name="quantity" class="form-control" placeholder="Nhập giá">
                            </div>
                            <div class="form-group">
                                <strong>Màu</strong>
                                <input type="text" name="color" class="form-control" placeholder="Nhập màu sắc">
                            </div>
                            <div class="form-group">
                                <strong>Ngày nhập kho</strong>
                                <input type="date" name="ngay_nhap" class="form-control">
                            </div>

                            <div class="form-group">
                                <label >Thuộc danh mục</label>
                                <select name="category_id" class="custom-select">
                                    @foreach($category as $key => $value)
                                        <option value="{{$value->id}}">{{$value->name}}</option>
                                    @endforeach
                                </select>
                            </div>
                        </div>
                    </div>
                    <button type="submit" class="btn btn-success mt-2">Lưu</button>
                </form>

            </div>
        </div>
    </div>
@endsection

resources/views/admin/category/index.blade.php
@extends('outline')

@section('content')
    <div class="container">
        <div class="card">
            <div class="card-header">
                <div class="row">
                    <div class="col-md-6">
                        <h4>Quản lý danh mục sản phẩm11111111111111111111</h4>
                    </div>
                    <div class="col-md-6">
                        <a href="{{route('category-product.create')}}" class="btn btn-primary float-end">
                            Thêm mới
                        </a>
                    </div>
                </div>
            </div>

            <div class="card-body">
                @if (session('status'))
                    <div class="alert alert-success">
                        {{ Session::get('status') }}
                    </div>
                @endif
                <table class = "table table-bordered">
                    <thead>
                        <tr>
                            <th>STT</th>
                            <th>Tên danh mục</th>
                            <th>Tùy chọn</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach($category as $key => $item)
                            <tr>
                                 <td>{{$key}}</td>
                                 <td>{{$item->name}}</td>
                                <td>
                                    <a href="{{route('category-product.edit',[$item->id])}}" class="btn btn-primary">Edit</a>
                                    <form action = "{{route('category-product.destroy',[$item->id])}}" method="POST">
                                        @method('DELETE')
                                        @csrf
                                        <button onclick="return confirm(' Bạn có chắc chắn muốn xóa chapter này không? ')" class = "btn btn-danger">Delete </button>
                                    </form>
                                </td>
                            </tr>
                        @endforeach
                    </tbody>
                </table>
            </div>
        </div>
    </div>