routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\IndexController;
use App\Http\Controllers\ProductController;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\CategoryProductController;
use App\Http\Controllers\PostController;
use App\Http\Controllers\FrontendController;
use App\Http\Controllers\CartController;
use App\Http\Controllers\Controller;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

//Route::get('/home123', function () {
//    return view('frontend.home');
//});
//Route::get('/clone', 'FrontendController@getHome');
//Route::get('/clone', [
//    'uses' => 'FrontendController@getHome'
//]);

Route::get('/clone', [FrontendController::class,'getHome']);
Route::get('detail/{id}/', [FrontendController::class,'getDetail']);
Route::post('detail/{id}/', [FrontendController::class,'postComment']);


Route::get('detail/{id}/', [FrontendController::class,'getDetail']);

Route::get('search', [FrontendController::class,'getSearch']);

Route::group(['prefix' => 'cart'], function() {
    Route::get('add/{id}', [CartController::class, 'getAddCart']);
    Route::get('show', [CartController::class, 'getShowCart']);
    Route::get('delete/{id}', [CartController::class, 'getDeleteCart']);
    Route::get('update', [CartController::class, 'getUpdateCart']);
    Route::post('show', [CartController::class, 'postComplete']);
});

Route::get('complete',[CartController::class, 'getComplete']);

//Route::get('cart/add/{id}', [CartController::class,'getAddCart']);

Route::get('category-product/{id}/', [FrontendController::class,'getCategoryProduct']);

Route::get('/', [IndexController::class,'home']);

Route::get('/home', [HomeController::class, 'index'])->name('home');
Route::get('/test', function () {
   return view('layouts.master');
});
Route::get('/thu', function () {
   return view('test');
});
Auth::routes();

Route::resource('admin/product', ProductController::class);
Route::resource('admin/category-product', CategoryProductController::class);
Route::resource('admin/post', PostController::class);

app/Models/CategoryProduct.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;
use App\Models\Product;
use Illuminate\Database\Eloquent\Relations\HasMany;

class CategoryProduct extends Model
{
    use HasFactory;
    protected $table = 'category_product';
    public $timestamps = false;
    protected $primaryKey = 'id';
    protected $fillable = [
        'name',
    ];

    public function product() : HasMany
    {
        return $this->hasMany(Product::class, 'category_id', 'id');
    }
}

app/Http/Controllers/CategoryProductController.php
<?php

namespace App\Http\Controllers;

use App\Models\CategoryProduct;
use Illuminate\Http\Request;

class   CategoryProductController extends Controller
{

    public function index()
    {
        $category = CategoryProduct::orderBy('id','DESC')->get();
        return view('admin.categoryproduct.index')->with(compact('category'));
    }


    public function create()
    {
        return view('admin.categoryproduct.create');
    }


    public function store(Request $request)
    {
        CategoryProduct::create($request->all());
      //  return redirect()->route('categoryproduct.index')->with('status', 'Thêm danh mục thành công');
        return redirect()->back()->with('status', 'Thêm danh mục thành công');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }


    public function edit($id)
    {
        $category = CategoryProduct::find($id);
        return view('admin.categoryproduct.edit')->with(compact('category'));
    }


    public function update(Request $request, $id)
    {
        $category = CategoryProduct::find($id);
        $category->update($request->all());
        return redirect()->route('category-product.index')->with('status','Cập nhật thành công');
    }


    public function destroy(CategoryProduct $categoryProduct)
    {
        $categoryProduct->delete();
        return redirect()->route('category-product.index')->with('status','Xóa thành công');
    }
}

resources/views/admin/categoryproduct/create.blade.php
@extends('outline')


@section('content')
    <div class="container">
        <div class="card">
            <div class="card-header">
                <div class="row">
                    <div class="col-md-6">
                        <h3>Thêm danh mục sản phẩm</h3>
                    </div>
                    <div class="col-md-6">
                        <a href="{{route('category-product.index')}}" class="btn btn-primary float-end">Danh sách danh mục sản phẩm</a>
                    </div>
                </div>
            </div>

            <div class="card-body">
                <form action="{{route('category-product.store')}}" method="POST">
                    @csrf
                    <div class="row">
                        <div class="col-md-6">
                            <div class="form-group">
                                <strong>Tên danh mục sản phẩm</strong>
                                <input type="text" name="name" class="form-control" placeholder="Nhập tên danh mục sản phẩm">
                            </div>
                        </div>
                    </div>
                    <button type="submit" class="btn btn-success mt-2">Lưu</button>
                </form>

            </div>
        </div>
    </div>
@endsection

resources/views/admin/categoryproduct/edit.blade.php
@extends('outline')


@section('content')
    <div class="container">
        <div class="card">
            <div class="card-header">
                <div class="row">
                    <div class="col-md-6">
                        <h3> Sửa danh mục</h3>
                    </div>
                    <div class="col-md-6">
                        <a href="{{route('category-product.index')}}" class="btn btn-primary float-end">Danh sách danh mục</a>
                    </div>
                </div>
            </div>

            <div class="card-body">
                <form action="{{route('category-product.update',$category->id)}}" method="POST">
                    @method('PUT')
                    @csrf
                    <div class="row">
                        <div class="col-md-6">
                            <div class="form-group">
                                <strong>Tên danh mục </strong>
                                <input type="text" name="name" value="{{$category->name}}" class="form-control" placeholder="Nhập tên danh mục">
                            </div>

                        </div>
                    </div>
                    <button type="submit" class="btn btn-success mt-2">Lưu</button>
                </form>

            </div>
        </div>
    </div>
@endsection

resources/views/admin/categoryproduct/index.blade.php
@extends('outline')

@section('content')
    <div class="container">
        <div class="card">
            <div class="card-header">
                <div class="row">
                    <div class="col-md-6">
                        <h4>Quản lý danh mục sản phẩm</h4>
                    </div>
                    <div class="col-md-6">
                        <a href="{{route('category-product.create')}}" class="btn btn-primary float-end">Thêm mới</a>
                    </div>
                </div>
            </div>

            <div class="card-body">
                @if (session('status'))
                    <div class="alert alert-success">
                        {{ Session::get('status') }}
                    </div>
                @endif
                <table class = "table table-bordered">
                    <thead>
                        <tr>
                            <th>STT</th>
                            <th>Tên danh mục</th>
                            <th>Tùy chọn</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach($category as $key => $item)
                            <tr>
                                 <td>{{++$key}}</td>
                                 <td>{{$item->name}}</td>
                                <td>
                                    <a href="{{route('category-product.edit',[$item->id])}}" class="btn btn-primary">Edit</a>
                                    <form action = "{{route('category-product.destroy',[$item->id])}}" method="POST">
                                        @method('DELETE')
                                        @csrf
                                        <button onclick="return confirm(' Bạn có chắc chắn muốn xóa chapter này không? ')" class = "btn btn-danger">Delete </button>
                                    </form>
                                </td>
                            </tr>
                        @endforeach
                    </tbody>
                </table>
            </div>
        </div>
    </div>
@endsection