routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\IndexController;
use App\Http\Controllers\ProductController;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\CategoryProductController;
use App\Http\Controllers\PostController;
use App\Http\Controllers\FrontendController;
use App\Http\Controllers\CartController;
use App\Http\Controllers\Controller;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

//Route::get('/home123', function () {
//    return view('frontend.home');
//});
//Route::get('/clone', 'FrontendController@getHome');
//Route::get('/clone', [
//    'uses' => 'FrontendController@getHome'
//]);

Route::get('/clone', [FrontendController::class,'getHome']);
Route::get('detail/{id}/', [FrontendController::class,'getDetail']);
Route::post('detail/{id}/', [FrontendController::class,'postComment']);


Route::get('detail/{id}/', [FrontendController::class,'getDetail']);

Route::get('search', [FrontendController::class,'getSearch']);

Route::group(['prefix' => 'cart'], function() {
    Route::get('add/{id}', [CartController::class, 'getAddCart']);
    Route::get('show', [CartController::class, 'getShowCart']);
    Route::get('delete/{id}', [CartController::class, 'getDeleteCart']);
    Route::get('update', [CartController::class, 'getUpdateCart']);
    Route::post('show', [CartController::class, 'postComplete']);
});

Route::get('complete',[CartController::class, 'getComplete']);

//Route::get('cart/add/{id}', [CartController::class,'getAddCart']);

Route::get('category-product/{id}/', [FrontendController::class,'getCategoryProduct']);

Route::get('/', [IndexController::class,'home']);

Route::get('/home', [HomeController::class, 'index'])->name('home');
Route::get('/test', function () {
   return view('layouts.master');
});
Route::get('/thu', function () {
   return view('test');
});
Auth::routes();

Route::resource('admin/product', ProductController::class);
Route::resource('admin/category-product', CategoryProductController::class);
Route::resource('admin/post', PostController::class);

app/Models/Product.php
<?php

namespace App\Models;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;
use Illuminate\Database\Eloquent\Relations\HasMany;
use App\Models\CategoryProduct;
class Product extends Model
{
    use HasFactory;
    protected $primaryKey = 'id';
    public $table = 'products';
    protected $fillable = [
        'name',
        'description',
        'price',
        'category_id',
        'quantity',
        'color',
        'stock_date',
        'hinhanh'
    ];
    public function categoryProduct()
    {
        return $this->belongsTo(CategoryProduct::class, 'category_id', 'id');
    }

}

app/Http/Controllers/ProductController.php
<?php

namespace App\Http\Controllers;
use App\Models\Product;
use App\Models\CategoryProduct;
use Illuminate\Http\Request;

class ProductController extends Controller
{

    public function index()
    {
        $product = Product::orderBy('id','DESC')->with('categoryProduct')->get();
        return view('admin.product.index')->with(compact('product'));
    }


    public function create()
    {
        $category = CategoryProduct::with('product')->orderBy('id','DESC')->get();
        return view('admin.product.create')->with(compact('category'));
    }


    public function store(Request $request)
    {
       // $data = $request->all();
        $data = $request->validate(
            [
                'name' => 'required',
                'description' => 'required',
                'hinhanh' => 'required|image|mimes: jpg,png,jpeg,gif,svg',
//                |max:10240|dimensions:min_width=100,
//                min_height=100,max_width=5000,max_height=5000',
                'price' => 'required',
                'category_id' => 'required',
                'quantity' => 'required',
                'color' => 'required',
                'stock_date' => 'required',
            ],
            [
                'name.unique' => 'Tên sản phẩm đã có, xin điền tên khác',
                'description.required' => 'Tên mô tả đã có, xin điền tên khác',
                'name.required' => 'Tên sản phẩm phải có nhé',
                'price.required' => 'Giá tiền phải có nhé',
                'color.required' => 'Màu sắc phải có nhé',
                'quantity.required' => 'Số lương phải có',
                'stock_date.required'=> 'Ngày nhập phải có'
            ]
        );
        $product = new Product();
        $product->name = $data['name'];
        $product->description = $data['description'];
        $product->price = $data['price'];
        $product->category_id = $data['category_id'];
        $product->quantity = $data['quantity'];
        $product->color = $data['color'];
        $product->stock_date = $data['stock_date'];
        $get_image = $request->hinhanh;
//        dd($get_image);
        $path = 'uploads/product/';
        $get_name_image = $get_image->getClientOriginalName();
        $name_image = current(explode('.',$get_name_image));
        $new_image = $name_image.rand(0,99).'.'.$get_image->getClientOriginalExtension();
        $get_image->move($path,$new_image);
        $product->hinhanh = $new_image;
        $product->save();


//     Product::create($request->all());

      return redirect()->route('product.index')->with('status', 'Thêm sản phẩm thành công');
  //      return redirect()->back()->with('status', 'Thêm sản phẩm thành công');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    public function edit($id)
    {
        $product = Product::find($id);
        $category = CategoryProduct::query()->orderBy('id', 'DESC')->get();
        return view('admin.product.edit')->with(compact('product','category'));
    }


    public function update(Request $request, $id)
    {
        $data = $request->validate(
            [
                'name' => 'required',
                'description' => 'required',
                'hinhanh' => 'required|image|mimes: jpg,png,jpeg,gif,svg',
//                |max:10240|dimensions:min_width=100,
//                min_height=100,max_width=5000,max_height=5000',
                'price' => 'required',
                'category_id' => 'required',
                'quantity' => 'required',
                'color' => 'required',
                'stock_date' => 'required',
            ],
            [
                'name.unique' => 'Tên sản phẩm đã có, xin điền tên khác',
                'description.required' => 'Tên mô tả đã có, xin điền tên khác',
                'name.required' => 'Tên sản phẩm phải có nhé',
                'price.required' => 'Giá tiền phải có nhé',
                'color.required' => 'Màu sắc phải có nhé',
                'quantity.required' => 'Số lương phải có',
                'stock_date.required'=> 'Ngày nhập phải có'
            ]
        );
        $product = Product::find($id);
        $product->name = $data['name'];
        $product->description  = $data['description'];
        $product->price = $data['price'];
        $product->category_id = $data['category_id'];
        $product->quantity = $data['quantity'];
        $product->color = $data['color'];
        $product->stock_date = $data['stock_date'];
        $get_image = $request->hinhanh;

        if ($get_image) {
            $path = 'uploads/product/'.$product->hinhanh;

            if (file_exists($path)) {
                unlink($path);
            }

            $path = 'uploads/product/';
            $get_name_image = $get_image->getClientOriginalName();
            $name_image = current(explode('.',$get_name_image));
            $new_image = $name_image.rand(0,99).'.'.$get_image->getClientOriginalExtension();
            $get_image->move($path,$new_image);
            $product->hinhanh = $new_image;


        }
        $product->save();

        return redirect()->route('product.index')->with('status','Cập nhật thành công');
    }


    public function destroy(Product $product)
    {
//        Product::find($id)->delete();

        $path = 'uploads/product'.$product->id;

        if(file_exists($path)) {
            unlink($path);
        }

        $product->delete();
        return redirect()->route('product.index')->with('status','Xóa thành công');
    }
}

resources/views/admin/product/create.blade.php
@extends('outline')


@section('content')
    <div class="container">
        <div class="card">
            <div class="card-header">
                <div class="row">
                    <div class="col-md-6">
                        <h3>Thêm sản phẩm</h3>
                    </div>
                    <div class="col-md-6">
                        <a href="{{route('product.index')}}" class="btn btn-primary float-end">Danh sách sản phẩm</a>
                    </div>
                </div>
            </div>

            <div class="card-body">
                <form action="{{route('product.store')}}" method="POST" enctype='multipart/form-data'>
                    @csrf
                    <div class="row">
                        <div class="col-md-6">
                            <div class="form-group">
                                <strong>Tên sản phẩm</strong>
                                <input type="text" name="name" class="form-control" placeholder="Nhập tên sản phẩm">
                            </div>
                            <div class="form-group">
                                <strong>Ảnh sản phẩm</strong>
                                <input type="file" class="form-control-file" name="hinhanh">
                            </div>


                            <div class="form-group">
                                <strong>Mô tả</strong>
                                <input type="text" name="description" class="form-control" placeholder="Nhập mô tả sản phẩm">
                            </div>
                            <div class="form-group">
                                <strong>Giá</strong>
                                <input type="text" name="price" class="form-control" placeholder="Nhập giá">
                            </div>
                            <div class="form-group">
                                <strong>Số lượng</strong>
                                <input type="number" name="quantity" class="form-control" placeholder="Nhập SL">
                            </div>
                            <div class="form-group">
                                <strong>Màu</strong>
                                <input type="text" name="color" class="form-control" placeholder="Nhập màu sắc">
                            </div>
                            <div class="form-group">
                                <strong>Ngày nhập kho</strong>
                                <input type="date" name="stock_date" class="form-control">
                            </div>

                            <div class="form-group">
                                <label >Thuộc danh mục</label>
                                <select name="category_id" class="custom-select">
                                    @foreach($category as $key => $value)
                                        <option value="{{$value->id}}">{{$value->name}}</option>
                                    @endforeach
                                </select>
                            </div>
                        </div>
                    </div>
                    <button type="submit" class="btn btn-success mt-2">Lưu</button>
                </form>

            </div>
        </div>
    </div>
@endsection

resources/views/admin/product/edit.blade.php
@extends('outline')


@section('content')
    <div class="container">
        <div class="card">
            <div class="card-header">
                <div class="row">
                    <div class="col-md-6">
                        <h3>Sửa sản phẩm</h3>
                    </div>
                    <div class="col-md-6">
                        <a href="{{route('product.index')}}" class="btn btn-primary float-end">Danh sách sản phẩm</a>
                    </div>
                </div>
            </div>
            @if ($errors->any())
                <div class = "alert alert-danger">
                    <ul>
                        @foreach($errors->all() as $error)
                            <li>{{$error}}</li>
                        @endforeach
                    </ul>
                </div>
            @endif
            <div class="card-body">
                <form action="{{route('product.update',[$product->id])}}" method="POST" enctype="multipart/form-data">
                    @method('PUT')
                    @csrf
                    <div class="row">
                        <div class="col-md-6">
                            <div class="form-group">
                                <strong>Tên sản phẩm</strong>
                                <input type="text" name="name" value="{{$product->name}}" class="form-control" placeholder="Nhập tên sản phẩm">
                            </div>
                            <div class="form-group">
                                <strong>Mô tả</strong>
                                <input type="text" name="description" value="{{$product->description}}" class="form-control" placeholder="Nhập mô tả sản phẩm">
                            </div>
                            <div class="form-group">
                                <label for="exampleInputEmail1">Hình ảnh sản phẩm</label>
                                <input type="file" class="form-control-file" name="hinhanh">
                                <td><img src="{{asset('uploads/product/'.$product->hinhanh)}}" height="250" width="180"></td>
                            </div>
                            <div class="form-group">
                                <strong>Giá</strong>
                                <input type="text" name="price" value="{{$product->price}}" class="form-control" placeholder="Nhập giá">
                            </div>
                            <div class="form-group">
                                <strong>Số lượng</strong>
                                <input type="number" name="quantity" value="{{$product->quantity}}" class="form-control" placeholder="Nhập giá">
                            </div>
                            <div class="form-group">
                                <strong>Màu</strong>
                                <input type="text" name="color" value="{{$product->color}}" class="form-control" placeholder="Nhập màu sắc">
                            </div>
                            <div class="form-group">
                                <strong>Ngày nhập kho</strong>
                                <input type="date" name="stock_date" value="{{$product->stock_date}}" class="form-control">
                            </div>

                            <div class="form-group">
                                <label >Thuộc danh mục</label>
                                <select name="category_id" class="custom-select">
                                    @foreach($category as $key => $value)
                                        <option {{$value->id == $product->category_id ? 'selected' : ''}}  value="{{$value->id}}">{{$value->name}}</option>
                                    @endforeach
                                </select>
                            </div>
                        </div>
                    </div>
                    <button type="submit" class="btn btn-success mt-2">Update</button>
                </form>

            </div>
        </div>
    </div>
@endsection

resources/views/admin/product/index.blade.php
@extends('outline')

@section('content')
    <div class="container">
        <div class="card">
            <div class="card-header">
                <div class="row">
                    <div class="col-md-6">
                        <h3>Quản lý sản phẩm </h3>
                    </div>
                    <div class="col-md-6">
                        <a href="{{route('product.create')}}" class="btn btn-primary float-end">Thêm mới</a>
                    </div>
                </div>
            </div>

            <div class="card-body">
                @if (session('status'))
                    <div class="alert alert-success">
                        {{ Session::get('status') }}
                    </div>
                @endif
                <table class = "table table-bordered">
                    <thead>
                        <tr>
                            <th>STT</th>
                            <th>Tên sản phẩm</th>
                            <th>Mô tả</th>
{{--                            <th>Giá</th>--}}
{{--                            <th>Màu sắc</th>--}}
                            <th>Thuộc danh mục</th>
                            <th>Tùy chọn</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach($product as $key => $item)
                            <tr>
                                <td>{{++$key}}</td>
                                <td>{{$item->name}}</td>
                                <td>{{$item->description}}</td>
                                <td><img src="{{asset('uploads/product/'.$item->hinhanh)}}" height="250" width="180"></td>
{{--                                <td>{{$item->price}}</td>--}}
{{--                                <td>{{$item->color}}</td>--}}
                                <td>{{$item->categoryProduct->name}}</td>
                                <td>
                                    <a href="{{route('product.edit',[$item->id])}}" class="btn btn-primary">Edit</a>
                                    <form action = "{{route('product.destroy',[$item->id])}}" method="POST">
                                        @method('DELETE')
                                        @csrf
                                        <button onclick="return confirm(' Bạn có chắc chắn muốn xóa chapter này không? ')" class = "btn btn-danger">Delete </button>
                                    </form>
                                </td>
                            </tr>
                        @endforeach
                    </tbody>
                </table>
            </div>
        </div>
    </div>
@endsection